/*
 * File:           StudentsHandler.java
 * Date:           March 24, 2015  2:32 PM
 *
 * @author  Zurab
 * @version generated by NetBeans XML module
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplicationxml;

import org.xml.sax.AttributeList;
import org.xml.sax.SAXException;

/**
 *
 * @author Zurab
 */
public interface StudentsHandler {

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_home(final String data, final AttributeList meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_students(final AttributeList meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_students() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_student(final AttributeList meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_student() throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_name(final String data, final AttributeList meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_addr(final AttributeList meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_addr() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_digest(final AttributeList meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_digest() throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_sname(final String data, final AttributeList meta) throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_date(final String data, final AttributeList meta) throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_city(final String data, final AttributeList meta) throws SAXException;
    
}
