/*
 * File:           StudentsHandlerImpl.java
 * Date:           March 24, 2015  2:32 PM
 *
 * @author  Zurab
 * @version generated by NetBeans XML module
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplicationxml;

import org.xml.sax.AttributeList;
import org.xml.sax.SAXException;

/**
 *
 * @author Zurab
 */
public class StudentsHandlerImpl implements StudentsHandler {
    public static final boolean DEBUG = false;

    public void handle_home(final String data, final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_home: " + meta);
        }
    }

    public void start_students(final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_students: " + meta);
        }
    }

    public void end_students() throws SAXException {
        if (DEBUG) {
            System.err.println("end_students()");
        }
    }

    public void start_student(final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_student: " + meta);
        }
    }

    public void end_student() throws SAXException {
        if (DEBUG) {
            System.err.println("end_student()");
        }
    }

    public void handle_name(final String data, final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_name: " + meta);
        }
    }

    public void start_addr(final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_addr: " + meta);
        }
    }

    public void end_addr() throws SAXException {
        if (DEBUG) {
            System.err.println("end_addr()");
        }
    }

    public void start_digest(final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("start_digest: " + meta);
        }
    }

    public void end_digest() throws SAXException {
        if (DEBUG) {
            System.err.println("end_digest()");
        }
    }

    public void handle_sname(final String data, final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_sname: " + meta);
        }
    }

    public void handle_date(final String data, final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_date: " + meta);
        }
    }

    public void handle_city(final String data, final AttributeList meta) throws SAXException {
        if (DEBUG) {
            System.err.println("handle_city: " + meta);
        }
    }
    
}
